// <auto-generated />
using FacultyAPI1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacultyAPI1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240626170017_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacultyAPI1.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            FacultyName = "Accounting and Informatics"
                        },
                        new
                        {
                            FacultyId = 2,
                            FacultyName = "Applied Sciences"
                        },
                        new
                        {
                            FacultyId = 3,
                            FacultyName = "Management Sciences"
                        },
                        new
                        {
                            FacultyId = 4,
                            FacultyName = "Engineering and the Built Environment"
                        },
                        new
                        {
                            FacultyId = 5,
                            FacultyName = "Health Sciences"
                        },
                        new
                        {
                            FacultyId = 6,
                            FacultyName = "Arts and Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
